# -*- coding: utf-8 -*-
"""BlendorBot-Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DntQeF5T_4tPLDAmsQq2o51bw7CW1jJK
"""

!pip install transformers

from transformers import pipeline, Conversation

# Initialize the conversational pipeline
chatbot = pipeline("conversational", model="facebook/blenderbot-400M-distill")

# Create a conversation object
conversation = Conversation() # Initialize an empty conversation

# Add the user's initial message
conversation.add_message({"role": "user", "content": "Hi, How are you..?"})


# Pass the conversation to the chatbot
response = chatbot(conversation)

# Print the latest generated response
print(response.generated_responses[-1])